steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/civiform/gcp-image', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/civiform/gcp-image']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'civiform-app', '--image', 'gcr.io/civiform/gcp-image', '--region', 'us-west1']
images:
- gcr.io/civiform/gcp-image
timeout: 1800s
